name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  test-app:
    name: Build and Test
    runs-on: windows-latest

    steps:
      - name: Check python version
        run: python --version

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      # - name: Run tests
      #   run: |
      #     python -m unittest discover -s tests -p "*.py"
